//
//  MainMenuModels.swift
//  CDRAssessment
//
//  Created by Diego Henrique Silva Oliveira on 03/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainMenu
{
    // MARK: Use cases
    enum FetchTexts
    {
        struct Request
        {
        }
        struct Response
        {
            var texts: [String]
        }
        struct ViewModel
        {
            struct DisplayedTexts
            {
                var title: String
                var subtitle: String
                var startButtonTitle: String
                var referenceButtonTitle: String
                var referenceStudyURL: URL
            }
            var displayedTexts: DisplayedTexts
        }
    }
}
