//
//  MainMenuRouter.swift
//  CDRAssessment
//
//  Created by Diego Henrique Silva Oliveira on 03/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainMenuRoutingLogic
{
    func routeToQuiz()
    func routeToReferencePage(url: URL)
}

protocol MainMenuDataPassing
{
    var dataStore: MainMenuDataStore? { get }
}

class MainMenuRouter: NSObject, MainMenuRoutingLogic, MainMenuDataPassing
{
    weak var viewController: MainMenuViewController?
    var dataStore: MainMenuDataStore?
    
    // MARK: Routing
    
    func routeToQuiz() {
        guard let viewController else { return }
        let destinationVC = QuizViewController.instantiate("Quiz")
        navigateToQuiz(source: viewController, destination: destinationVC)
    }
    
    func routeToReferencePage(url: URL) {
        let destination = UIApplication.shared
        navigateToReferencePage(source: viewController!, destination: destination, url: url)
    }
    
    // MARK: Navigation
    
    func navigateToQuiz(source: MainMenuViewController, destination: QuizViewController)
    {
      source.show(destination, sender: nil)
    }
    
    func navigateToReferencePage(source: MainMenuViewController, destination: UIApplication, url: URL)
    {
        destination.open(url)
    }
}
