//
//  MainMenuPresenter.swift
//  CDRAssessment
//
//  Created by Diego Henrique Silva Oliveira on 03/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainMenuPresentationLogic
{
    func presentTexts(response: MainMenu.FetchTexts.Response)
}

class MainMenuPresenter: MainMenuPresentationLogic
{
    weak var viewController: MainMenuDisplayLogic?
    
    // MARK: Do something
    
    func presentTexts(response: MainMenu.FetchTexts.Response)
    {
        guard let referenceStudyURL = URL(string: response.texts[4]) else { return }
        
        let displayedTexts = MainMenu.FetchTexts.ViewModel.DisplayedTexts(
            title: response.texts[0],
            subtitle: response.texts[1],
            startButtonTitle: response.texts[2],
            referenceButtonTitle: response.texts[3],
            referenceStudyURL: referenceStudyURL
        )
        
        let viewModel = MainMenu.FetchTexts.ViewModel(displayedTexts: displayedTexts)
        viewController?.displayFetchedTexts(viewModel: viewModel)
    }
}
