//
//  MainMenuPresenter.swift
//  CDRAssessment
//
//  Created by Diego Henrique Silva Oliveira on 03/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainMenuPresentationLogic
{
  func presentSomething(response: MainMenu.Something.Response)
}

class MainMenuPresenter: MainMenuPresentationLogic
{
  weak var viewController: MainMenuDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MainMenu.Something.Response)
  {
    let viewModel = MainMenu.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
